---

name: super-claims
director_uuid: 63ddb6a6-d6fe-40e1-b16b-2ff6b2034c79

releases:
  - {name: zookeeper_release, version: latest}
  - {name: kafka_release, version: latest}


instance_groups:
  - name: zoo_node
    instances: 1
    azs: [z1]
    jobs:
    - name: zookeeper_server
      release: zookeeper_release
      provides:
        zookeeper: {as: zookeeper}
      consumes:
        zookeeper: {from: zookeeper}
    resource_pool: default
    persistent_disk_type: default
    networks:
      - name: default
  - name: kafka_node
    instances: 1
    azs: [z1]
    jobs:
    - name: kafka_server
      release: kafka_release
      provides:
        kafka: {as: kafka}
      consumes:
        zookeeper: {from: zookeeper}
        kafka: {from: kafka}
      properties:
        auto_create_topics: true
        default_replication_factor: 1
    resource_pool: default
    persistent_disk_type: default
    networks:
      - name: default

update:
  canaries: 1
  max_in_flight: 10
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
